# Generated by Django 4.2.7 on 2023-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
    ]
